name: live-face-render
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - attrs==25.3.0
      - cffi==1.17.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==24.2
      - pillow==11.1.0
      - protobuf==4.25.6
      - pycparser==2.22
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - six==1.17.0
      - sounddevice==0.5.1
      - tqdm==4.67.1
      - zipp==3.21.0
